spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/jktlms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  security:    user:      name: 'in28minutes'
      password: 'dummy'
    
server:  port: 8000