spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/itimersalesforce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:  port: 8000